// Comprehensive ingredient database with detailed information
import { DetailedIngredientInfo, IngredientCategory } from './types';

export const COMPREHENSIVE_INGREDIENTS: DetailedIngredientInfo[] = [
  // VEGETABLES
  {
    id: 'tomato-001',
    name: 'Tomato',
    category: 'vegetable' as IngredientCategory,
    aliases: ['Roma tomato', 'Cherry tomato', 'Beefsteak tomato', 'Plum tomato'],
    description: 'A versatile fruit commonly used as a vegetable, rich in lycopene and vitamin C. Essential for Mediterranean and global cuisines.',
    season: ['summer', 'early fall'],
    origin: 'South America (Peru, Ecuador)',
    nutrition: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.6,
      sodium: 5,
      potassium: 237,
      vitamins: {
        'Vitamin C': 28,
        'Vitamin K': 10,
        'Folate': 4,
        'Vitamin A': 5,
        'Vitamin B6': 4,
        'Thiamine': 3,
      },
      minerals: {
        'Potassium': 7,
        'Manganese': 5,
        'Phosphorus': 2,
        'Magnesium': 3,
        'Iron': 1,
      },
      antioxidants: ['lycopene', 'beta-carotene', 'naringenin', 'chlorogenic acid'],
    },
    freshness: {
      goodIndicators: [
        'Firm, smooth skin without blemishes',
        'Vibrant red color (for ripe tomatoes)',
        'Fresh, earthy, slightly sweet smell',
        'Feels heavy for its size',
        'Green stem attachment present',
        'Slight give when gently pressed (ripe)',
      ],
      badIndicators: [
        'Wrinkled, cracked, or split skin',
        'Soft spots, dark patches, or bruises',
        'Moldy or black stem area',
        'Sour, fermented, or alcoholic smell',
        'Overly soft or mushy texture',
        'Pale or dull color',
      ],
      optimalRipeness: 'Slight give when gently pressed, deep red color, sweet aroma at stem end',
      shelfLife: {
        roomTemp: '3-7 days (depending on ripeness)',
        refrigerated: '1-2 weeks (ripe), 2-3 weeks (green)',
        frozen: '6-12 months (cooked or blanched)',
      },
    },
    compatibility: {
      flavorProfile: ['sweet', 'acidic', 'umami', 'fresh'],
      cookingMethods: ['raw', 'sautéed', 'roasted', 'grilled', 'blanched', 'stewed', 'pureed'],
      pairsWellWith: {
        herbs: ['basil', 'oregano', 'thyme', 'parsley', 'rosemary', 'cilantro', 'mint'],
        vegetables: ['onions', 'garlic', 'bell peppers', 'zucchini', 'eggplant', 'cucumber'],
        proteins: ['mozzarella', 'feta', 'chicken', 'fish', 'beans', 'eggs', 'prosciutto'],
        grains: ['pasta', 'rice', 'bread', 'quinoa', 'couscous'],
        other: ['olive oil', 'balsamic vinegar', 'lemon', 'avocado', 'olives'],
      },
      avoidPairings: ['strong spices that overpower delicate flavor', 'very sweet fruits'],
    },
    healthBenefits: {
      primary: [
        'Heart health support (lycopene reduces cardiovascular risk)',
        'Immune system boost (high Vitamin C content)',
        'Bone health maintenance (Vitamin K)',
        'Antioxidant protection against free radicals',
        'Skin health and UV protection',
      ],
      secondary: [
        'Eye health (lutein and zeaxanthin)',
        'Cancer prevention (especially prostate)',
        'Hydration support (94% water content)',
        'Blood pressure regulation',
        'Digestive health',
      ],
      warnings: ['May cause acid reflux in sensitive individuals', 'High in histamine (may trigger allergies)'],
    },
    recipeSuggestions: {
      raw: ['Caprese salad', 'Bruschetta', 'Gazpacho', 'Fresh salsa', 'Tomato sandwich'],
      cooked: ['Pasta sauce', 'Tomato soup', 'Ratatouille', 'Stuffed tomatoes', 'Tomato curry'],
      preserved: ['Sun-dried tomatoes', 'Tomato paste', 'Canned tomatoes', 'Tomato jam'],
    },
    storageInstructions: 'Store at room temperature until ripe, then refrigerate. Never refrigerate unripe tomatoes as it stops ripening process. Store stem-side down to prevent moisture loss.',
    preparationTips: [
      'Score an X on the bottom and blanch in boiling water for easy peeling',
      'Remove seeds and juice for less watery dishes',
      'Salt sliced tomatoes and drain for 15 minutes to remove excess moisture',
      'Use a sharp serrated knife to avoid crushing',
      'Room temperature tomatoes have better flavor than cold ones',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'onion-001',
    name: 'Onion',
    category: 'vegetable' as IngredientCategory,
    aliases: ['Yellow onion', 'White onion', 'Red onion', 'Sweet onion', 'Vidalia onion'],
    description: 'A fundamental aromatic vegetable that forms the base of countless dishes worldwide. Rich in sulfur compounds that provide health benefits.',
    season: ['fall', 'winter', 'spring'],
    origin: 'Central Asia (Afghanistan, Pakistan)',
    nutrition: {
      calories: 40,
      protein: 1.1,
      carbs: 9.3,
      fat: 0.1,
      fiber: 1.7,
      sugar: 4.2,
      sodium: 4,
      potassium: 146,
      vitamins: {
        'Vitamin C': 12,
        'Vitamin B6': 6,
        'Folate': 5,
        'Thiamine': 3,
        'Biotin': 1,
      },
      minerals: {
        'Manganese': 6,
        'Potassium': 4,
        'Phosphorus': 3,
        'Copper': 2,
        'Chromium': 2,
      },
      antioxidants: ['quercetin', 'anthocyanins', 'sulfur compounds'],
    },
    freshness: {
      goodIndicators: [
        'Firm, dry outer skin (papery texture)',
        'No soft spots or dark patches',
        'Heavy for size',
        'No sprouting or green shoots',
        'Intact outer layers',
        'No strong odor when uncut',
      ],
      badIndicators: [
        'Soft, mushy, or spongy texture',
        'Dark spots, mold, or black patches',
        'Strong ammonia or sulfur smell',
        'Green sprouts growing from top',
        'Wet or slimy outer skin',
        'Hollow or dried out center',
      ],
      optimalRipeness: 'Firm with dry, papery skin, no sprouting, heavy for size',
      shelfLife: {
        roomTemp: '2-3 months (whole, in cool, dry place)',
        refrigerated: '3-4 months (whole), 7-10 days (cut)',
        frozen: '6-8 months (chopped), 3-4 months (whole)',
      },
    },
    compatibility: {
      flavorProfile: ['sharp', 'pungent', 'sweet when cooked', 'savory', 'sulfurous'],
      cookingMethods: ['raw', 'sautéed', 'roasted', 'grilled', 'caramelized', 'pickled', 'deep-fried'],
      pairsWellWith: {
        herbs: ['thyme', 'rosemary', 'sage', 'bay leaves', 'parsley', 'chives'],
        vegetables: ['garlic', 'carrots', 'celery', 'bell peppers', 'mushrooms', 'potatoes'],
        proteins: ['beef', 'chicken', 'pork', 'fish', 'beans', 'lentils', 'cheese'],
        grains: ['rice', 'pasta', 'bread', 'barley', 'quinoa'],
        other: ['olive oil', 'butter', 'wine', 'vinegar', 'stock'],
      },
    },
    healthBenefits: {
      primary: [
        'Anti-inflammatory properties (quercetin)',
        'Heart health support (sulfur compounds)',
        'Immune system boost (vitamin C, antioxidants)',
        'Blood sugar regulation',
        'Digestive health (prebiotic fibers)',
      ],
      secondary: [
        'Bone health (sulfur compounds)',
        'Cancer prevention (organosulfur compounds)',
        'Antimicrobial properties',
        'Respiratory health',
        'Cholesterol management',
      ],
      warnings: ['May cause digestive upset in sensitive individuals', 'Can trigger heartburn or acid reflux'],
    },
    recipeSuggestions: {
      raw: ['Red onion salad', 'Pickle relish', 'Fresh salsa', 'Onion rings (battered)'],
      cooked: ['French onion soup', 'Caramelized onions', 'Onion confit', 'Stuffed onions'],
      preserved: ['Pickled onions', 'Dehydrated onions', 'Onion powder', 'Frozen diced onions'],
    },
    storageInstructions: 'Store in a cool, dry, well-ventilated area away from light. Keep away from potatoes (they release moisture). Use mesh bags or baskets for air circulation.',
    preparationTips: [
      'Chill onion in freezer for 10-15 minutes before cutting to reduce tears',
      'Use a very sharp knife for clean cuts',
      'Keep root end intact when slicing to hold layers together',
      'Rinse cut onions under cold water to reduce sharpness',
      'Soak in cold water for 10 minutes to mellow raw flavor',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'spinach-001',
    name: 'Spinach',
    category: 'vegetable' as IngredientCategory,
    aliases: ['Baby spinach', 'Mature spinach', 'Flat-leaf spinach', 'Savoy spinach'],
    description: 'A nutrient-dense leafy green vegetable packed with iron, vitamins, and minerals. One of the most nutritious vegetables available.',
    season: ['spring', 'fall', 'winter'],
    origin: 'Persia (modern-day Iran)',
    nutrition: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
      sodium: 79,
      potassium: 558,
      vitamins: {
        'Vitamin K': 604,
        'Vitamin A': 188,
        'Folate': 49,
        'Vitamin C': 47,
        'Vitamin E': 10,
        'Vitamin B6': 10,
        'Thiamine': 6,
        'Riboflavin': 11,
      },
      minerals: {
        'Iron': 15,
        'Manganese': 45,
        'Magnesium': 20,
        'Potassium': 16,
        'Calcium': 10,
        'Phosphorus': 5,
        'Zinc': 4,
        'Copper': 7,
      },
      antioxidants: ['lutein', 'zeaxanthin', 'beta-carotene', 'kaempferol', 'quercetin'],
    },
    freshness: {
      goodIndicators: [
        'Bright, vibrant green color',
        'Crisp, firm leaves',
        'No yellowing or browning',
        'Fresh, earthy smell',
        'Dry leaves (not wet or slimy)',
        'No wilting or drooping',
      ],
      badIndicators: [
        'Yellowing, browning, or dark spots',
        'Wilted, slimy, or mushy texture',
        'Musty or sour smell',
        'Excessive moisture or condensation',
        'Holes from insects',
        'Overly mature thick stems',
      ],
      optimalRipeness: 'Young, tender leaves with bright green color and crisp texture',
      shelfLife: {
        roomTemp: '1-2 days (not recommended)',
        refrigerated: '5-7 days (fresh), 3-5 days (bagged)',
        frozen: '10-12 months (blanched), 6-8 months (raw)',
      },
    },
    compatibility: {
      flavorProfile: ['mild', 'earthy', 'slightly bitter', 'mineral', 'green'],
      cookingMethods: ['raw', 'sautéed', 'steamed', 'wilted', 'blanched', 'creamed', 'baked'],
      pairsWellWith: {
        herbs: ['garlic', 'nutmeg', 'dill', 'parsley', 'chives', 'tarragon'],
        vegetables: ['mushrooms', 'onions', 'tomatoes', 'bell peppers', 'artichokes'],
        proteins: ['feta cheese', 'ricotta', 'eggs', 'chicken', 'salmon', 'bacon'],
        grains: ['pasta', 'rice', 'quinoa', 'phyllo pastry', 'bread'],
        other: ['olive oil', 'lemon', 'pine nuts', 'parmesan', 'cream', 'butter'],
      },
    },
    healthBenefits: {
      primary: [
        'Eye health (lutein, zeaxanthin prevent macular degeneration)',
        'Bone health (extremely high Vitamin K)',
        'Iron for blood health and oxygen transport',
        'Immune support (high Vitamin C)',
        'Heart health (nitrates, potassium)',
      ],
      secondary: [
        'Cancer prevention (antioxidants)',
        'Brain health (folate, vitamin K)',
        'Digestive health (fiber)',
        'Skin health (vitamin A)',
        'Energy production (B vitamins)',
        'Muscle function (magnesium)',
      ],
      warnings: ['High in oxalates - limit if prone to kidney stones', 'May interfere with blood thinners (high Vitamin K)'],
    },
    recipeSuggestions: {
      raw: ['Spinach salad', 'Green smoothies', 'Sandwich greens', 'Spinach pesto'],
      cooked: ['Sautéed spinach', 'Spinach soup', 'Spinach quiche', 'Creamed spinach', 'Spinach lasagna'],
      preserved: ['Frozen spinach', 'Dehydrated spinach', 'Spinach powder'],
    },
    storageInstructions: 'Store unwashed in original packaging or breathable bag in refrigerator. Wash just before use. Remove any damaged leaves to prevent spoilage.',
    preparationTips: [
      'Wash thoroughly in cold water (sand can hide in leaves)',
      'Remove thick stems and damaged leaves',
      'Spin dry in salad spinner or pat with paper towels',
      'Cook briefly to retain nutrients and prevent mushiness',
      'Add to dishes at the end of cooking to prevent overcooking',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  // FRUITS
  {
    id: 'apple-001',
    name: 'Apple',
    category: 'fruit' as IngredientCategory,
    aliases: ['Red apple', 'Green apple', 'Granny Smith', 'Gala', 'Fuji', 'Honeycrisp'],
    description: 'One of the most popular and versatile fruits worldwide. Rich in fiber, vitamins, and antioxidants with natural sweetness.',
    season: ['fall', 'winter'],
    origin: 'Central Asia (Kazakhstan)',
    nutrition: {
      calories: 52,
      protein: 0.3,
      carbs: 14,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10.4,
      sodium: 1,
      potassium: 107,
      vitamins: {
        'Vitamin C': 8,
        'Vitamin K': 2,
        'Vitamin A': 1,
        'Folate': 1,
        'Vitamin E': 1,
      },
      minerals: {
        'Potassium': 3,
        'Manganese': 2,
        'Copper': 2,
        'Phosphorus': 1,
        'Magnesium': 1,
      },
      antioxidants: ['quercetin', 'catechin', 'chlorogenic acid', 'anthocyanins'],
    },
    freshness: {
      goodIndicators: [
        'Firm, solid texture',
        'Bright, vibrant color',
        'Smooth, unblemished skin',
        'Fresh, sweet aroma',
        'Heavy for size',
        'Crisp sound when tapped',
      ],
      badIndicators: [
        'Soft spots, bruises, or wrinkles',
        'Brown or dark patches',
        'Mealy or mushy texture',
        'Fermented or alcoholic smell',
        'Holes or insect damage',
        'Shriveled or wrinkled skin',
      ],
      optimalRipeness: 'Firm, crisp texture with bright color and sweet aroma',
      shelfLife: {
        roomTemp: '1-2 weeks',
        refrigerated: '4-6 weeks',
        frozen: '8-12 months (sliced)',
      },
    },
    compatibility: {
      flavorProfile: ['sweet', 'tart', 'crisp', 'refreshing'],
      cookingMethods: ['raw', 'baked', 'sautéed', 'roasted', 'stewed', 'dehydrated'],
      pairsWellWith: {
        herbs: ['cinnamon', 'nutmeg', 'ginger', 'thyme', 'rosemary'],
        vegetables: ['onions', 'celery', 'carrots', 'cabbage'],
        proteins: ['pork', 'chicken', 'turkey', 'cheddar cheese', 'walnuts'],
        grains: ['oats', 'bread', 'pastry', 'quinoa'],
        other: ['honey', 'lemon', 'caramel', 'vanilla', 'maple syrup'],
      },
    },
    healthBenefits: {
      primary: [
        'Heart health (fiber, antioxidants)',
        'Digestive health (pectin fiber)',
        'Blood sugar regulation',
        'Weight management (low calorie, high fiber)',
        'Immune support (vitamin C)',
      ],
      secondary: [
        'Brain health (quercetin)',
        'Bone health (boron)',
        'Lung health (antioxidants)',
        'Cancer prevention',
        'Hydration (85% water)',
      ],
      warnings: ['Seeds contain amygdalin (avoid eating in large quantities)'],
    },
    recipeSuggestions: {
      raw: ['Apple slices', 'Waldorf salad', 'Apple coleslaw', 'Fruit salad'],
      cooked: ['Apple pie', 'Apple crisp', 'Baked apples', 'Apple sauce', 'Apple butter'],
      preserved: ['Dried apples', 'Apple chips', 'Apple juice', 'Apple cider vinegar'],
    },
    storageInstructions: 'Store in refrigerator crisper drawer. Keep away from other fruits as apples release ethylene gas. Wrap individually to prevent moisture loss.',
    preparationTips: [
      'Wash thoroughly before eating (especially if not organic)',
      'Brush with lemon juice to prevent browning',
      'Core before cooking to remove seeds',
      'Peel if desired, but skin contains most nutrients',
      'Choose variety based on use (tart for cooking, sweet for eating)',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'banana-001',
    name: 'Banana',
    category: 'fruit' as IngredientCategory,
    aliases: ['Cavendish banana', 'Plantain', 'Lady finger banana', 'Red banana'],
    description: 'A tropical fruit rich in potassium, vitamin B6, and natural sugars. Perfect for quick energy and versatile in cooking.',
    season: ['year-round'],
    origin: 'Southeast Asia (Malaysia, Philippines)',
    nutrition: {
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12.2,
      sodium: 1,
      potassium: 358,
      vitamins: {
        'Vitamin B6': 20,
        'Vitamin C': 15,
        'Folate': 5,
        'Riboflavin': 4,
        'Niacin': 4,
      },
      minerals: {
        'Potassium': 10,
        'Manganese': 13,
        'Magnesium': 7,
        'Copper': 4,
        'Phosphorus': 2,
      },
      antioxidants: ['dopamine', 'catechins', 'gallocatechin'],
    },
    freshness: {
      goodIndicators: [
        'Bright yellow color (ripe)',
        'Firm but slightly soft texture',
        'Sweet, fruity aroma',
        'No dark spots or bruises',
        'Green tips (if wanting to ripen)',
        'Plump, full shape',
      ],
      badIndicators: [
        'Extensive brown or black spots',
        'Mushy or overly soft texture',
        'Split or cracked skin',
        'Fermented or alcoholic smell',
        'Moldy stem end',
        'Shriveled or dried appearance',
      ],
      optimalRipeness: 'Yellow with small brown spots (sweet), green-yellow (less sweet)',
      shelfLife: {
        roomTemp: '3-7 days (depending on ripeness)',
        refrigerated: '7-14 days (ripe), extends life but may brown',
        frozen: '6-8 months (peeled, sliced)',
      },
    },
    compatibility: {
      flavorProfile: ['sweet', 'mild', 'creamy', 'tropical'],
      cookingMethods: ['raw', 'baked', 'fried', 'grilled', 'mashed', 'blended'],
      pairsWellWith: {
        herbs: ['cinnamon', 'vanilla', 'nutmeg', 'ginger', 'mint'],
        vegetables: ['none commonly'],
        proteins: ['peanut butter', 'almond butter', 'yogurt', 'milk', 'eggs'],
        grains: ['oats', 'bread', 'pancakes', 'cereal', 'rice'],
        other: ['honey', 'chocolate', 'coconut', 'berries', 'citrus'],
      },
    },
    healthBenefits: {
      primary: [
        'Heart health (potassium regulates blood pressure)',
        'Energy boost (natural sugars, B6)',
        'Digestive health (fiber, prebiotics)',
        'Muscle function (potassium, magnesium)',
        'Mood regulation (vitamin B6, tryptophan)',
      ],
      secondary: [
        'Exercise recovery (potassium, carbs)',
        'Bone health (manganese)',
        'Immune support (vitamin C)',
        'Antioxidant protection',
        'Blood sugar regulation (resistant starch)',
      ],
      warnings: ['High in sugar - moderate for diabetics', 'May cause bloating in sensitive individuals'],
    },
    recipeSuggestions: {
      raw: ['Banana smoothie', 'Fruit salad', 'Banana bread', 'Banana split'],
      cooked: ['Banana pancakes', 'Banana muffins', 'Fried plantains', 'Banana foster'],
      preserved: ['Banana chips', 'Dried banana', 'Banana flour', 'Frozen banana'],
    },
    storageInstructions: 'Store at room temperature to ripen. Refrigerate ripe bananas to slow ripening (skin will brown but fruit stays good). Separate from bunch to slow ripening.',
    preparationTips: [
      'Buy at different stages of ripeness for continuous supply',
      'Freeze overripe bananas for smoothies or baking',
      'Brush with citrus juice to prevent browning',
      'Use ripe bananas for sweetness in baking',
      'Green bananas are starchier and less sweet',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // PROTEINS
  {
    id: 'chicken-breast-001',
    name: 'Chicken Breast',
    category: 'protein' as IngredientCategory,
    aliases: ['Boneless chicken breast', 'Skinless chicken breast', 'Chicken fillet'],
    description: 'Lean, versatile protein source that is low in fat and high in protein. A staple in healthy cooking worldwide.',
    season: ['year-round'],
    origin: 'Domesticated worldwide',
    nutrition: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
      sugar: 0,
      sodium: 74,
      potassium: 256,
      vitamins: {
        'Niacin': 69,
        'Vitamin B6': 32,
        'Pantothenic Acid': 13,
        'Vitamin B12': 5,
        'Riboflavin': 5,
        'Thiamine': 4,
      },
      minerals: {
        'Phosphorus': 20,
        'Selenium': 27,
        'Potassium': 7,
        'Magnesium': 6,
        'Zinc': 6,
        'Iron': 3,
      },
      antioxidants: ['selenium', 'vitamin E'],
    },
    freshness: {
      goodIndicators: [
        'Pink to white color',
        'Firm, elastic texture',
        'Minimal liquid in package',
        'Fresh, neutral smell',
        'No slimy or sticky feel',
        'Uniform color throughout',
      ],
      badIndicators: [
        'Gray, green, or yellow discoloration',
        'Slimy, sticky, or tacky texture',
        'Strong, unpleasant, or sour odor',
        'Excessive liquid or blood',
        'Soft or mushy texture',
        'Dark spots or patches',
      ],
      optimalRipeness: 'Fresh, firm texture with pink-white color and neutral smell',
      shelfLife: {
        roomTemp: '2 hours maximum (danger zone)',
        refrigerated: '1-2 days (fresh), 3-4 days (cooked)',
        frozen: '9-12 months (raw), 2-3 months (cooked)',
      },
    },
    compatibility: {
      flavorProfile: ['mild', 'neutral', 'savory', 'lean'],
      cookingMethods: ['grilled', 'baked', 'sautéed', 'poached', 'fried', 'roasted', 'braised'],
      pairsWellWith: {
        herbs: ['thyme', 'rosemary', 'sage', 'oregano', 'basil', 'parsley', 'tarragon'],
        vegetables: ['broccoli', 'carrots', 'onions', 'peppers', 'mushrooms', 'tomatoes'],
        proteins: ['bacon', 'ham', 'cheese', 'eggs', 'nuts'],
        grains: ['rice', 'pasta', 'quinoa', 'bread', 'couscous'],
        other: ['lemon', 'garlic', 'olive oil', 'butter', 'wine', 'stock'],
      },
    },
    healthBenefits: {
      primary: [
        'High-quality complete protein (muscle building)',
        'Weight management (low fat, high protein)',
        'Heart health (lean protein, niacin)',
        'Energy metabolism (B vitamins)',
        'Immune support (selenium, protein)',
      ],
      secondary: [
        'Bone health (phosphorus, protein)',
        'Brain function (choline, B vitamins)',
        'Antioxidant protection (selenium)',
        'Red blood cell formation (B12)',
        'Nervous system health (B6)',
      ],
      warnings: ['Must be cooked to 165°F internal temperature', 'Risk of salmonella if undercooked'],
    },
    recipeSuggestions: {
      raw: ['Chicken tartare (with proper handling)', 'Chicken sushi (sashimi-grade)'],
      cooked: ['Grilled chicken', 'Chicken stir-fry', 'Chicken soup', 'Chicken curry', 'Baked chicken'],
      preserved: ['Chicken jerky', 'Canned chicken', 'Frozen chicken meals'],
    },
    storageInstructions: 'Store in coldest part of refrigerator (below 40°F). Keep in original packaging or airtight container. Use within 1-2 days or freeze immediately.',
    preparationTips: [
      'Pound to even thickness for uniform cooking',
      'Brine for 30 minutes for juicier meat',
      'Use meat thermometer to ensure 165°F internal temp',
      'Let rest 5 minutes after cooking',
      'Marinate for at least 30 minutes for flavor',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // DAIRY
  {
    id: 'milk-001',
    name: 'Milk',
    category: 'dairy' as IngredientCategory,
    aliases: ['Whole milk', 'Skim milk', '2% milk', 'Low-fat milk', 'Cow\'s milk'],
    description: 'A nutritious dairy product rich in calcium, protein, and vitamins. Essential for bone health and versatile in cooking.',
    season: ['year-round'],
    origin: 'Domesticated cattle worldwide',
    nutrition: {
      calories: 61,
      protein: 3.2,
      carbs: 4.8,
      fat: 3.3,
      fiber: 0,
      sugar: 4.8,
      sodium: 43,
      potassium: 150,
      vitamins: {
        'Vitamin B12': 18,
        'Riboflavin': 17,
        'Vitamin A': 5,
        'Vitamin D': 10,
        'Pantothenic Acid': 9,
        'Thiamine': 3,
      },
      minerals: {
        'Calcium': 12,
        'Phosphorus': 10,
        'Potassium': 4,
        'Zinc': 4,
        'Magnesium': 3,
        'Selenium': 4,
      },
      antioxidants: ['vitamin A', 'vitamin E', 'selenium'],
    },
    freshness: {
      goodIndicators: [
        'White or slightly off-white color',
        'Smooth, creamy texture',
        'Fresh, clean, slightly sweet smell',
        'No lumps or curdling',
        'Within expiration date',
        'Cold temperature when purchased',
      ],
      badIndicators: [
        'Sour, rancid, or off smell',
        'Lumpy, curdled, or separated texture',
        'Yellowish or discolored appearance',
        'Thick or slimy consistency',
        'Past expiration date',
        'Warm temperature',
      ],
      optimalRipeness: 'Fresh, cold, smooth texture with clean smell',
      shelfLife: {
        roomTemp: '2 hours maximum',
        refrigerated: '5-7 days past sell-by date',
        frozen: '1-3 months (may separate when thawed)',
      },
    },
    compatibility: {
      flavorProfile: ['mild', 'creamy', 'slightly sweet', 'rich'],
      cookingMethods: ['raw', 'heated', 'steamed', 'scalded', 'reduced'],
      pairsWellWith: {
        herbs: ['vanilla', 'cinnamon', 'nutmeg', 'cardamom'],
        vegetables: ['none commonly'],
        proteins: ['eggs', 'cheese', 'yogurt', 'butter'],
        grains: ['cereal', 'oats', 'bread', 'pancakes', 'rice'],
        other: ['honey', 'chocolate', 'coffee', 'tea', 'fruit'],
      },
    },
    healthBenefits: {
      primary: [
        'Bone health (calcium, vitamin D, phosphorus)',
        'Muscle building (complete protein)',
        'Teeth health (calcium, phosphorus)',
        'Vitamin B12 source (nerve function)',
        'Hydration and electrolyte balance',
      ],
      secondary: [
        'Heart health (potassium)',
        'Immune support (vitamin A)',
        'Energy metabolism (B vitamins)',
        'Antioxidant protection',
        'Sleep quality (tryptophan)',
      ],
      warnings: ['Lactose intolerance may cause digestive issues', 'High in saturated fat (whole milk)'],
    },
    recipeSuggestions: {
      raw: ['Drinking milk', 'Cereal', 'Smoothies', 'Milk shakes'],
      cooked: ['Hot chocolate', 'Creamy soups', 'Puddings', 'Custards', 'Baked goods'],
      preserved: ['Powdered milk', 'Evaporated milk', 'Condensed milk'],
    },
    storageInstructions: 'Store in coldest part of refrigerator (not door). Keep in original container. Use within 5-7 days of opening.',
    preparationTips: [
      'Smell before using - sour smell indicates spoilage',
      'Shake well if separated (normal for some types)',
      'Heat gently to avoid scorching',
      'Use in baking for moisture and richness',
      'Substitute with plant-based alternatives if needed',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // GRAINS
  {
    id: 'rice-001',
    name: 'Rice',
    category: 'grain' as IngredientCategory,
    aliases: ['White rice', 'Brown rice', 'Jasmine rice', 'Basmati rice', 'Wild rice'],
    description: 'A staple grain that feeds more than half the world\'s population. Versatile, gluten-free, and available in many varieties.',
    season: ['year-round'],
    origin: 'Asia (China, India)',
    nutrition: {
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fat: 0.3,
      fiber: 0.4,
      sugar: 0.1,
      sodium: 1,
      potassium: 55,
      vitamins: {
        'Thiamine': 6,
        'Niacin': 8,
        'Folate': 2,
        'Vitamin B6': 5,
      },
      minerals: {
        'Manganese': 55,
        'Selenium': 11,
        'Phosphorus': 4,
        'Magnesium': 3,
        'Copper': 4,
      },
      antioxidants: ['selenium', 'manganese'],
    },
    freshness: {
      goodIndicators: [
        'Uniform color and size',
        'Dry, hard texture',
        'Clean, neutral smell',
        'No insect damage',
        'No moisture or clumping',
        'Clear, not cloudy (for white rice)',
      ],
      badIndicators: [
        'Musty, moldy, or sour smell',
        'Visible insects or insect holes',
        'Discolored or off-color grains',
        'Excessive broken grains',
        'Moisture or clumping',
        'Dusty appearance',
      ],
      optimalRipeness: 'Dry, uniform grains with neutral smell',
      shelfLife: {
        roomTemp: '4-6 years (white), 6 months (brown)',
        refrigerated: '6-8 years (white), 1 year (brown)',
        frozen: '30 years (white), 18 months (brown)',
      },
    },
    compatibility: {
      flavorProfile: ['neutral', 'mild', 'slightly nutty', 'starchy'],
      cookingMethods: ['boiled', 'steamed', 'fried', 'baked', 'risotto', 'pilaf'],
      pairsWellWith: {
        herbs: ['cilantro', 'parsley', 'thyme', 'bay leaves', 'saffron'],
        vegetables: ['onions', 'carrots', 'peas', 'bell peppers', 'mushrooms'],
        proteins: ['chicken', 'fish', 'shrimp', 'beans', 'tofu', 'eggs'],
        grains: ['none commonly mixed'],
        other: ['soy sauce', 'coconut milk', 'stock', 'butter', 'olive oil'],
      },
    },
    healthBenefits: {
      primary: [
        'Energy source (complex carbohydrates)',
        'Gluten-free (safe for celiac disease)',
        'Easy to digest',
        'B vitamins for metabolism',
        'Selenium for antioxidant protection',
      ],
      secondary: [
        'Heart health (whole grain varieties)',
        'Weight management (filling, low fat)',
        'Bone health (manganese)',
        'Nervous system health (B vitamins)',
        'Immune support (selenium)',
      ],
      warnings: ['High glycemic index (white rice)', 'May contain arsenic (wash before cooking)'],
    },
    recipeSuggestions: {
      raw: ['Rice salad (cooked and cooled)', 'Sushi rice'],
      cooked: ['Fried rice', 'Rice pilaf', 'Risotto', 'Rice pudding', 'Stuffed peppers'],
      preserved: ['Rice cakes', 'Rice crackers', 'Rice flour', 'Rice vinegar'],
    },
    storageInstructions: 'Store in airtight container in cool, dry place. Keep away from moisture and pests. Use oldest rice first.',
    preparationTips: [
      'Rinse until water runs clear to remove excess starch',
      'Use 1:2 ratio of rice to water for most types',
      'Let stand 5 minutes after cooking before fluffing',
      'Toast rice in dry pan before cooking for nutty flavor',
      'Add salt and oil to cooking water for flavor',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // SPICES
  {
    id: 'garlic-001',
    name: 'Garlic',
    category: 'spice' as IngredientCategory,
    aliases: ['Fresh garlic', 'Garlic cloves', 'Elephant garlic', 'Black garlic'],
    description: 'A pungent, aromatic bulb that\'s essential in cuisines worldwide. Known for its powerful flavor and health benefits.',
    season: ['year-round'],
    origin: 'Central Asia',
    nutrition: {
      calories: 42,
      protein: 1.8,
      carbs: 9.3,
      fat: 0.1,
      fiber: 0.6,
      sugar: 0.3,
      sodium: 6,
      potassium: 153,
      vitamins: {
        'Vitamin C': 52,
        'Vitamin B6': 62,
        'Thiamine': 7,
        'Riboflavin': 3,
      },
      minerals: {
        'Manganese': 84,
        'Selenium': 6,
        'Phosphorus': 5,
        'Calcium': 6,
        'Iron': 9,
      },
      antioxidants: ['allicin', 'alliin', 'ajoene'],
    },
    freshness: {
      goodIndicators: [
        'Firm, solid bulbs',
        'Papery, dry outer skin',
        'No soft spots or sprouting',
        'Heavy for size',
        'Individual cloves feel firm',
        'Strong, pungent aroma when cut',
      ],
      badIndicators: [
        'Soft, mushy, or spongy texture',
        'Green sprouts growing from cloves',
        'Dark spots or mold',
        'Hollow or dried out feel',
        'Papery skin peeling excessively',
        'Mild or no aroma',
      ],
      optimalRipeness: 'Firm bulbs with tight, dry skin and strong aroma',
      shelfLife: {
        roomTemp: '3-6 months (whole bulb)',
        refrigerated: '2-3 weeks (peeled cloves)',
        frozen: '6-12 months (peeled, chopped)',
      },
    },
    compatibility: {
      flavorProfile: ['pungent', 'sharp', 'savory', 'aromatic', 'spicy'],
      cookingMethods: ['raw', 'sautéed', 'roasted', 'grilled', 'confit', 'pickled'],
      pairsWellWith: {
        herbs: ['parsley', 'basil', 'oregano', 'thyme', 'rosemary', 'cilantro'],
        vegetables: ['onions', 'tomatoes', 'peppers', 'mushrooms', 'spinach'],
        proteins: ['chicken', 'fish', 'beef', 'lamb', 'shrimp', 'tofu'],
        grains: ['pasta', 'rice', 'bread', 'quinoa'],
        other: ['olive oil', 'butter', 'lemon', 'ginger', 'wine'],
      },
    },
    healthBenefits: {
      primary: [
        'Immune system boost (allicin)',
        'Heart health (reduces blood pressure)',
        'Antimicrobial properties',
        'Anti-inflammatory effects',
        'Antioxidant protection',
      ],
      secondary: [
        'Cholesterol reduction',
        'Cancer prevention',
        'Brain health',
        'Digestive health',
        'Respiratory health',
      ],
      warnings: ['May cause bad breath and body odor', 'Can interfere with blood thinners'],
    },
    recipeSuggestions: {
      raw: ['Aioli', 'Garlic bread', 'Salad dressing', 'Pesto'],
      cooked: ['Roasted garlic', 'Garlic confit', 'Stir-fries', 'Soups', 'Sauces'],
      preserved: ['Pickled garlic', 'Garlic powder', 'Garlic salt', 'Garlic oil'],
    },
    storageInstructions: 'Store whole bulbs in cool, dry, well-ventilated place. Keep peeled cloves in refrigerator in oil or water.',
    preparationTips: [
      'Crush cloves to release allicin compounds',
      'Let chopped garlic sit 10 minutes before cooking for health benefits',
      'Remove green germ from center for milder flavor',
      'Use garlic press for easy mincing',
      'Rub hands with lemon to remove odor',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // COMMON PROTEINS
  {
    id: 'eggs-001',
    name: 'Eggs',
    category: 'protein' as IngredientCategory,
    aliases: ['Chicken eggs', 'Whole eggs', 'Fresh eggs'],
    description: 'A complete protein source with all essential amino acids, perfect for breakfast, baking, and cooking.',
    season: ['year-round'],
    origin: 'Domesticated worldwide',
    nutrition: {
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fat: 11,
      fiber: 0,
      sugar: 1.1,
      sodium: 124,
      potassium: 138,
      vitamins: {
        'Vitamin B12': 46,
        'Vitamin D': 20,
        'Vitamin A': 19,
        'Riboflavin': 42,
        'Folate': 12,
        'Vitamin B6': 6,
      },
      minerals: {
        'Selenium': 56,
        'Phosphorus': 20,
        'Iron': 12,
        'Zinc': 11,
        'Calcium': 6,
      },
      antioxidants: ['lutein', 'zeaxanthin', 'choline'],
    },
    freshness: {
      goodIndicators: [
        'Clean, uncracked shell',
        'Heavy for size',
        'No smell when cracked',
        'Firm, round yolk',
        'Thick, clear white',
      ],
      badIndicators: [
        'Cracked or dirty shell',
        'Sulfur smell',
        'Runny, flat yolk',
        'Thin, watery white',
        'Floats in water',
      ],
      optimalRipeness: 'Fresh eggs sink in water, older eggs float',
      shelfLife: {
        roomTemp: '2-3 weeks',
        refrigerated: '4-6 weeks',
        frozen: '12 months (beaten eggs only)',
      },
    },
    compatibility: {
      flavorProfile: ['neutral', 'rich', 'creamy'],
      cookingMethods: ['boiled', 'fried', 'scrambled', 'poached', 'baked'],
      pairsWellWith: {
        herbs: ['chives', 'parsley', 'dill', 'basil'],
        vegetables: ['tomatoes', 'spinach', 'mushrooms', 'peppers'],
        proteins: ['bacon', 'ham', 'cheese', 'salmon'],
        grains: ['bread', 'rice', 'pasta'],
        other: ['butter', 'cream', 'olive oil', 'salt', 'pepper'],
      },
      avoidPairings: ['strong fish', 'overly spicy ingredients'],
    },
    healthBenefits: {
      primary: [
        'Complete protein source',
        'Brain health (choline)',
        'Eye health (lutein, zeaxanthin)',
        'Muscle building and repair',
        'Vitamin D for bone health',
      ],
      secondary: [
        'Heart health support',
        'Weight management',
        'Antioxidant protection',
        'Energy production',
      ],
      warnings: ['High cholesterol content', 'Potential allergen', 'Salmonella risk if undercooked'],
    },
    recipeSuggestions: {
      raw: ['Mayonnaise', 'Meringue', 'Eggnog'],
      cooked: ['Scrambled eggs', 'Omelets', 'Quiche', 'Fried rice', 'Pasta carbonara'],
      preserved: ['Pickled eggs', 'Dehydrated eggs'],
    },
    storageInstructions: 'Store in refrigerator, pointed end down. Keep in original carton to prevent odor absorption.',
    preparationTips: [
      'Bring to room temperature before baking',
      'Crack into separate bowl first to check freshness',
      'Use older eggs for hard-boiling (easier to peel)',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },

  // COMMON VEGETABLES
  {
    id: 'carrot-001',
    name: 'Carrot',
    category: 'vegetable' as IngredientCategory,
    aliases: ['Baby carrots', 'Orange carrots', 'Fresh carrots'],
    description: 'A crunchy, sweet root vegetable rich in beta-carotene and fiber, great raw or cooked.',
    season: ['fall', 'winter', 'spring'],
    origin: 'Central Asia',
    nutrition: {
      calories: 41,
      protein: 0.9,
      carbs: 9.6,
      fat: 0.2,
      fiber: 2.8,
      sugar: 4.7,
      sodium: 69,
      potassium: 320,
      vitamins: {
        'Vitamin A': 334,
        'Vitamin K': 16,
        'Vitamin C': 7,
        'Vitamin B6': 7,
        'Folate': 5,
      },
      minerals: {
        'Potassium': 9,
        'Manganese': 7,
        'Phosphorus': 4,
        'Magnesium': 3,
      },
      antioxidants: ['beta-carotene', 'alpha-carotene', 'lutein'],
    },
    freshness: {
      goodIndicators: [
        'Firm, bright orange color',
        'Smooth skin',
        'Fresh green tops (if attached)',
        'No soft spots',
        'Crisp snap when broken',
      ],
      badIndicators: [
        'Soft, bendy texture',
        'White spots or slime',
        'Wilted or slimy tops',
        'Black spots or mold',
        'Strong smell',
      ],
      optimalRipeness: 'Firm, bright orange, smooth skin',
      shelfLife: {
        roomTemp: '1-2 weeks',
        refrigerated: '3-4 weeks',
        frozen: '10-12 months (blanched)',
      },
    },
    compatibility: {
      flavorProfile: ['sweet', 'earthy', 'mild'],
      cookingMethods: ['raw', 'roasted', 'steamed', 'boiled', 'sautéed', 'grilled'],
      pairsWellWith: {
        herbs: ['parsley', 'thyme', 'dill', 'ginger'],
        vegetables: ['onions', 'celery', 'potatoes', 'peas'],
        proteins: ['chicken', 'beef', 'lamb', 'fish'],
        grains: ['rice', 'quinoa', 'barley'],
        other: ['honey', 'butter', 'olive oil', 'lemon'],
      },
      avoidPairings: ['overly acidic ingredients'],
    },
    healthBenefits: {
      primary: [
        'Eye health (beta-carotene converts to Vitamin A)',
        'Immune system support',
        'Skin health',
        'Digestive health (fiber)',
        'Heart health',
      ],
      secondary: [
        'Blood sugar regulation',
        'Cancer prevention',
        'Brain health',
        'Anti-inflammatory properties',
      ],
      warnings: ['High sugar content for diabetics', 'Excessive consumption may cause skin discoloration'],
    },
    recipeSuggestions: {
      raw: ['Carrot sticks', 'Carrot salad', 'Coleslaw', 'Juice'],
      cooked: ['Roasted carrots', 'Carrot soup', 'Carrot cake', 'Stir-fry', 'Glazed carrots'],
      preserved: ['Pickled carrots', 'Dehydrated carrots'],
    },
    storageInstructions: 'Remove green tops, store in refrigerator crisper drawer in perforated plastic bag.',
    preparationTips: [
      'Scrub well or peel before eating',
      'Cut diagonally for stir-fries',
      'Cook with fat to increase beta-carotene absorption',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },

  // COMMON FRUITS
  {
    id: 'lemon-001',
    name: 'Lemon',
    category: 'fruit' as IngredientCategory,
    aliases: ['Fresh lemon', 'Citrus lemon', 'Yellow lemon'],
    description: 'A tart, acidic citrus fruit essential for cooking, baking, and beverages.',
    season: ['year-round'],
    origin: 'Asia',
    nutrition: {
      calories: 17,
      protein: 0.6,
      carbs: 5.4,
      fat: 0.2,
      fiber: 1.6,
      sugar: 1.5,
      sodium: 1,
      potassium: 80,
      vitamins: {
        'Vitamin C': 51,
        'Folate': 2,
        'Vitamin B6': 4,
      },
      minerals: {
        'Potassium': 2,
        'Calcium': 3,
        'Magnesium': 2,
      },
      antioxidants: ['limonene', 'citric acid', 'flavonoids'],
    },
    freshness: {
      goodIndicators: [
        'Bright yellow color',
        'Firm, heavy for size',
        'Smooth, thin skin',
        'Fresh citrus smell',
        'No soft spots',
      ],
      badIndicators: [
        'Dull, pale color',
        'Soft or mushy texture',
        'Wrinkled or thick skin',
        'Moldy spots',
        'Dry or hard texture',
      ],
      optimalRipeness: 'Bright yellow, firm, aromatic',
      shelfLife: {
        roomTemp: '1 week',
        refrigerated: '3-4 weeks',
        frozen: '3-4 months (juice/zest)',
      },
    },
    compatibility: {
      flavorProfile: ['tart', 'acidic', 'bright', 'citrusy'],
      cookingMethods: ['zested', 'juiced', 'candied', 'preserved'],
      pairsWellWith: {
        herbs: ['thyme', 'rosemary', 'mint', 'basil'],
        vegetables: ['garlic', 'onions', 'artichokes'],
        proteins: ['chicken', 'fish', 'lamb', 'seafood'],
        grains: ['rice', 'pasta', 'bread'],
        other: ['olive oil', 'butter', 'capers', 'olives'],
      },
      avoidPairings: ['milk (may curdle)', 'overly sweet ingredients'],
    },
    healthBenefits: {
      primary: [
        'Immune system boost (Vitamin C)',
        'Digestive health',
        'Kidney stone prevention',
        'Iron absorption enhancement',
        'Antioxidant protection',
      ],
      secondary: [
        'Heart health',
        'Skin health',
        'Weight management',
        'Cancer prevention',
      ],
      warnings: ['May erode tooth enamel', 'Can cause heartburn in sensitive individuals'],
    },
    recipeSuggestions: {
      raw: ['Lemonade', 'Salad dressing', 'Marinades', 'Garnish'],
      cooked: ['Lemon cake', 'Lemon chicken', 'Lemon pasta', 'Preserves'],
      preserved: ['Preserved lemons', 'Lemon zest', 'Lemon curd'],
    },
    storageInstructions: 'Store at room temperature for up to a week, refrigerate for longer storage.',
    preparationTips: [
      'Roll before juicing for more juice',
      'Zest before juicing',
      'Microwave for 10 seconds for easier juicing',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },

  // COMMON DAIRY
  {
    id: 'cheese-cheddar-001',
    name: 'Cheddar Cheese',
    category: 'dairy' as IngredientCategory,
    aliases: ['Sharp cheddar', 'Mild cheddar', 'Aged cheddar', 'Cheddar'],
    description: 'A firm, aged cheese with a sharp, tangy flavor, perfect for melting and snacking.',
    season: ['year-round'],
    origin: 'England',
    nutrition: {
      calories: 403,
      protein: 25,
      carbs: 1.3,
      fat: 33,
      fiber: 0,
      sugar: 0.5,
      sodium: 621,
      potassium: 98,
      vitamins: {
        'Vitamin A': 29,
        'Vitamin B12': 58,
        'Riboflavin': 22,
        'Vitamin K': 3,
      },
      minerals: {
        'Calcium': 72,
        'Phosphorus': 51,
        'Zinc': 26,
        'Selenium': 26,
      },
      antioxidants: ['conjugated linoleic acid'],
    },
    freshness: {
      goodIndicators: [
        'Firm texture',
        'Uniform color',
        'Fresh, tangy smell',
        'No mold (unless blue cheese)',
        'No oily surface',
      ],
      badIndicators: [
        'Slimy texture',
        'Off colors or spots',
        'Ammonia smell',
        'Excessive mold',
        'Bitter taste',
      ],
      optimalRipeness: 'Firm, aromatic, good color',
      shelfLife: {
        roomTemp: '2-4 hours',
        refrigerated: '3-4 weeks (unopened), 1-2 weeks (opened)',
        frozen: '6-8 months (texture changes)',
      },
    },
    compatibility: {
      flavorProfile: ['sharp', 'tangy', 'rich', 'nutty'],
      cookingMethods: ['melted', 'grated', 'sliced', 'cubed'],
      pairsWellWith: {
        herbs: ['chives', 'thyme', 'rosemary'],
        vegetables: ['tomatoes', 'onions', 'peppers', 'broccoli'],
        proteins: ['ham', 'bacon', 'chicken', 'beef'],
        grains: ['bread', 'crackers', 'pasta', 'rice'],
        other: ['wine', 'beer', 'apples', 'nuts'],
      },
      avoidPairings: ['very delicate flavors that it might overpower'],
    },
    healthBenefits: {
      primary: [
        'Bone health (calcium)',
        'Protein for muscle building',
        'Vitamin B12 for nerve function',
        'Dental health',
        'Satiety and weight management',
      ],
      secondary: [
        'Heart health (in moderation)',
        'Brain health',
        'Immune support',
      ],
      warnings: ['High in saturated fat', 'High sodium content', 'Lactose intolerance', 'High calorie content'],
    },
    recipeSuggestions: {
      raw: ['Cheese board', 'Sandwiches', 'Salads', 'Snacks'],
      cooked: ['Mac and cheese', 'Grilled cheese', 'Cheese sauce', 'Casseroles', 'Pizza'],
      preserved: ['Aged cheddar', 'Cheese powder'],
    },
    storageInstructions: 'Wrap in wax paper or cheese paper, store in refrigerator cheese drawer.',
    preparationTips: [
      'Bring to room temperature before serving',
      'Grate when cold for easier handling',
      'Use lower temperatures when melting to prevent separation',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },

  // COMMON GRAINS
  {
    id: 'bread-001',
    name: 'Bread',
    category: 'grain' as IngredientCategory,
    aliases: ['White bread', 'Whole wheat bread', 'Sliced bread', 'Loaf bread'],
    description: 'A staple food made from flour and water, perfect for sandwiches, toast, and meals.',
    season: ['year-round'],
    origin: 'Ancient civilizations worldwide',
    nutrition: {
      calories: 265,
      protein: 9,
      carbs: 49,
      fat: 3.2,
      fiber: 2.7,
      sugar: 5,
      sodium: 491,
      potassium: 115,
      vitamins: {
        'Thiamine': 47,
        'Niacin': 36,
        'Folate': 28,
        'Riboflavin': 18,
      },
      minerals: {
        'Selenium': 39,
        'Manganese': 37,
        'Phosphorus': 11,
        'Iron': 20,
      },
      antioxidants: ['phenolic compounds', 'lignans'],
    },
    freshness: {
      goodIndicators: [
        'Soft, springy texture',
        'Fresh, yeasty smell',
        'No mold spots',
        'Uniform color',
        'Moist but not sticky',
      ],
      badIndicators: [
        'Hard, stale texture',
        'Moldy spots',
        'Sour smell',
        'Dry, crumbly texture',
        'Discoloration',
      ],
      optimalRipeness: 'Fresh, soft, aromatic',
      shelfLife: {
        roomTemp: '2-4 days',
        refrigerated: '1-2 weeks',
        frozen: '3-6 months',
      },
    },
    compatibility: {
      flavorProfile: ['mild', 'neutral', 'slightly sweet'],
      cookingMethods: ['toasted', 'baked', 'grilled', 'fried'],
      pairsWellWith: {
        herbs: ['rosemary', 'thyme', 'oregano', 'basil'],
        vegetables: ['tomatoes', 'lettuce', 'onions', 'avocado'],
        proteins: ['ham', 'turkey', 'chicken', 'cheese', 'eggs'],
        grains: ['oats', 'seeds', 'nuts'],
        other: ['butter', 'olive oil', 'honey', 'jam'],
      },
      avoidPairings: ['overly wet ingredients that make it soggy'],
    },
    healthBenefits: {
      primary: [
        'Energy source (carbohydrates)',
        'B vitamins for metabolism',
        'Fiber for digestion (whole grain)',
        'Protein for muscle maintenance',
        'Iron for blood health',
      ],
      secondary: [
        'Heart health (whole grain)',
        'Brain function',
        'Satiety',
      ],
      warnings: ['Gluten content', 'High carbohydrate content', 'Refined flour concerns (white bread)'],
    },
    recipeSuggestions: {
      raw: ['Sandwiches', 'Bread crumbs', 'Croutons'],
      cooked: ['French toast', 'Bread pudding', 'Stuffing', 'Grilled cheese'],
      preserved: ['Breadcrumbs', 'Dried bread', 'Rusks'],
    },
    storageInstructions: 'Store in cool, dry place in original packaging or bread box. Freeze for longer storage.',
    preparationTips: [
      'Toast for better texture and flavor',
      'Freeze extra slices for quick use',
      'Use stale bread for breadcrumbs or French toast',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },

  // COMMON SPICES
  {
    id: 'salt-001',
    name: 'Salt',
    category: 'spice' as IngredientCategory,
    aliases: ['Table salt', 'Sea salt', 'Kosher salt', 'Rock salt'],
    description: 'An essential mineral used for seasoning and preserving food, enhancing natural flavors.',
    season: ['year-round'],
    origin: 'Worldwide (sea, mines)',
    nutrition: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
      fiber: 0,
      sugar: 0,
      sodium: 38758,
      potassium: 8,
      vitamins: {},
      minerals: {
        'Sodium': 100,
        'Chloride': 100,
      },
      antioxidants: [],
    },
    freshness: {
      goodIndicators: [
        'Dry, free-flowing crystals',
        'No clumping',
        'Clean, pure appearance',
        'No foreign odors',
        'Uniform crystal size',
      ],
      badIndicators: [
        'Clumpy, caked texture',
        'Discoloration',
        'Foreign particles',
        'Moisture absorption',
        'Off odors',
      ],
      optimalRipeness: 'Dry, free-flowing, pure',
      shelfLife: {
        roomTemp: 'Indefinite (with proper storage)',
        refrigerated: 'Not necessary',
        frozen: 'Not necessary',
      },
    },
    compatibility: {
      flavorProfile: ['salty', 'enhancing', 'mineral'],
      cookingMethods: ['seasoning', 'preserving', 'brining', 'curing'],
      pairsWellWith: {
        herbs: ['all herbs and spices'],
        vegetables: ['all vegetables'],
        proteins: ['all proteins'],
        grains: ['all grains'],
        other: ['all foods'],
      },
      avoidPairings: ['none - universal seasoning'],
    },
    healthBenefits: {
      primary: [
        'Essential electrolyte balance',
        'Muscle and nerve function',
        'Fluid balance regulation',
        'Nutrient absorption',
      ],
      secondary: [
        'Blood pressure regulation (in moderation)',
        'Prevents dehydration',
        'Supports adrenal function',
      ],
      warnings: ['High blood pressure risk', 'Kidney strain', 'Water retention', 'Cardiovascular issues'],
    },
    recipeSuggestions: {
      raw: ['Seasoning', 'Salads', 'Rim for cocktails'],
      cooked: ['All cooking applications', 'Baking', 'Boiling water'],
      preserved: ['Curing meats', 'Pickling', 'Fermentation'],
    },
    storageInstructions: 'Store in airtight container in cool, dry place. Add rice grains to prevent clumping.',
    preparationTips: [
      'Taste as you go',
      'Add gradually - you can always add more',
      'Different salts have different intensities',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },

  {
    id: 'pepper-black-001',
    name: 'Black Pepper',
    category: 'spice' as IngredientCategory,
    aliases: ['Ground black pepper', 'Whole peppercorns', 'Pepper'],
    description: 'The most common spice, providing heat and flavor to dishes worldwide.',
    season: ['year-round'],
    origin: 'India',
    nutrition: {
      calories: 251,
      protein: 10.4,
      carbs: 64,
      fat: 3.3,
      fiber: 25,
      sugar: 0.6,
      sodium: 20,
      potassium: 1329,
      vitamins: {
        'Vitamin K': 163,
        'Vitamin C': 21,
        'Vitamin A': 13,
        'Vitamin E': 7,
      },
      minerals: {
        'Iron': 198,
        'Manganese': 567,
        'Calcium': 44,
        'Magnesium': 44,
      },
      antioxidants: ['piperine', 'volatile oils'],
    },
    freshness: {
      goodIndicators: [
        'Strong, pungent aroma',
        'Dark color',
        'Dry, whole peppercorns',
        'No dust or powder residue',
        'Fresh, spicy smell',
      ],
      badIndicators: [
        'Weak or no aroma',
        'Faded color',
        'Excessive dust',
        'Musty smell',
        'Clumping',
      ],
      optimalRipeness: 'Fresh, aromatic, properly dried',
      shelfLife: {
        roomTemp: '2-3 years (whole), 1-2 years (ground)',
        refrigerated: 'Not necessary',
        frozen: 'Not necessary',
      },
    },
    compatibility: {
      flavorProfile: ['spicy', 'pungent', 'warm', 'aromatic'],
      cookingMethods: ['ground fresh', 'whole', 'cracked', 'infused'],
      pairsWellWith: {
        herbs: ['all herbs', 'especially thyme', 'rosemary'],
        vegetables: ['all vegetables'],
        proteins: ['all proteins', 'especially beef', 'chicken'],
        grains: ['all grains'],
        other: ['salt', 'lemon', 'garlic', 'onion'],
      },
      avoidPairings: ['very delicate dishes where it might overpower'],
    },
    healthBenefits: {
      primary: [
        'Digestive health',
        'Antioxidant properties',
        'Anti-inflammatory effects',
        'Nutrient absorption enhancement',
        'Metabolism boost',
      ],
      secondary: [
        'Brain health',
        'Respiratory health',
        'Cancer prevention',
        'Heart health',
      ],
      warnings: ['May cause irritation in large amounts', 'Can trigger sneezing'],
    },
    recipeSuggestions: {
      raw: ['Seasoning', 'Spice blends', 'Rubs'],
      cooked: ['All cooking applications', 'Soups', 'Stews', 'Grilled meats'],
      preserved: ['Pickling spice', 'Cured meats'],
    },
    storageInstructions: 'Store in airtight container away from light and heat. Grind fresh for best flavor.',
    preparationTips: [
      'Grind fresh peppercorns for best flavor',
      'Add at end of cooking to preserve heat',
      'Toast whole peppercorns for deeper flavor',
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
];

export const SAMPLE_INGREDIENTS = COMPREHENSIVE_INGREDIENTS;

// Helper function to get ingredient info by name
export const getIngredientInfo = (name: string): DetailedIngredientInfo | undefined => {
  return COMPREHENSIVE_INGREDIENTS.find(
    ingredient => 
      ingredient.name.toLowerCase() === name.toLowerCase() ||
      ingredient.aliases.some(alias => alias.toLowerCase() === name.toLowerCase())
  );
};

// Helper function to get all ingredients by category
export const getIngredientsByCategory = (category: IngredientCategory): DetailedIngredientInfo[] => {
  return COMPREHENSIVE_INGREDIENTS.filter(ingredient => ingredient.category === category);
};

// Helper function to search ingredients by name, alias, or description
export const searchIngredients = (query: string): DetailedIngredientInfo[] => {
  const searchTerm = query.toLowerCase();
  return COMPREHENSIVE_INGREDIENTS.filter(ingredient =>
    ingredient.name.toLowerCase().includes(searchTerm) ||
    ingredient.aliases.some(alias => alias.toLowerCase().includes(searchTerm)) ||
    ingredient.description.toLowerCase().includes(searchTerm) ||
    ingredient.category.toLowerCase().includes(searchTerm)
  );
};
